name: t3-stack
display_name: "T3 Stack"
description: The "T3 Stack" - a type-safe, end-to-end full-stack application using Next.js, tRPC, Prisma, and Tailwind CSS. Optimized for type safety and developer productivity.
version: "1.0.0"
keywords:
  - web
  - full-stack
  - nextjs
  - react
  - trpc
  - prisma
  - typescript
  - tailwind
  - t3
stack:
  frontend:
    name: Next.js with React
    language: TypeScript
    framework: React
    styling: Tailwind CSS
  backend:
    name: Next.js API Routes + tRPC
    language: TypeScript
    framework: tRPC
    orm: Prisma
  database:
    name: PostgreSQL / MySQL / SQLite
    version: Flexible
suggested_epics:
  - name: Developer Infrastructure
    description: Testing (Vitest + Playwright), CI/CD pipeline (GitHub Actions + Vercel), linting (ESLint), error tracking (Sentry), Prisma migrations
    stories_estimate: 3-5
    priority: 0
    phase: foundation
    
  - name: Authentication with NextAuth.js
    description: Implement secure authentication using NextAuth.js with multiple providers (Google, GitHub, email).
    stories_estimate: 5-8
  - name: Type-Safe API Layer
    description: Build tRPC routers with end-to-end type safety, input validation with Zod.
    stories_estimate: 7-10
  - name: Database Schema & Migrations
    description: Design Prisma schema, implement migrations, and set up database seeding.
    stories_estimate: 5-7
  - name: UI Component Library
    description: Build reusable UI components with Tailwind CSS and headless UI patterns.
    stories_estimate: 8-12
pre_configured_patterns:
  - name: End-to-End Type Safety
    description: Automatic type inference from database to frontend with Prisma + tRPC.
  - name: React Query Integration
    description: Built-in data fetching, caching, and optimistic updates via tRPC.
  - name: Zod Validation
    description: Runtime validation with compile-time type inference.

# External services to consider (Buy vs Build)
external_services:
  auth:
    recommended: clerk
    alternatives: [nextauth, lucia]
    reason: "Best Next.js integration, 10k MAU free"
  database:
    recommended: planetscale
    alternatives: [neon, supabase]
    reason: "MySQL with Prisma, branching included"
  payments:
    recommended: stripe
    reason: "Best API, type-safe with trpc"
  email:
    recommended: resend
    alternatives: [postmark]
    reason: "React email templates"
  analytics:
    recommended: vercel-analytics
    alternatives: [posthog]
    reason: "Zero-config with Next.js"
  error_tracking:
    recommended: sentry
    reason: "Next.js + tRPC support"


# Visual testing configuration
visual_testing:
  platform: web
  strategy: browser-mcp
  pattern_file: "visual-testing/web.mdc"
  breakpoints:
    mobile: 375
    tablet: 768
    desktop: 1024
    wide: 1280
  tools:
    primary: playwright
    storybook: true
    visual_regression: chromatic
  agent_commands:
    screenshot: "browser_take_screenshot"
    audit_a11y: "runAccessibilityAudit"
    audit_perf: "runPerformanceAudit"
    playwright_test: "npx playwright test"
    playwright_update: "npx playwright test --update-snapshots"
  ci_integration:
    on_pr: true
    block_on_diff: true
