/**
 * Tests that the Speck git hooks Speck installs are actually REACHABLE.
 *
 * THE SCAR: installPreCommitHook() appended its loader to an existing hook with
 * `hookContent.trimEnd() + '\n\n' + loaderContent`, unconditionally and with no
 * reachability check. A pre-commit.com generated hook terminates in
 * `exec … -mpre_commit "${ARGS[@]}"` — `exec` REPLACES the shell process, so nothing
 * after it can ever run. Speck's block landed below that line, chmod +x reported
 * success, the marker was present in the file, and every commit-path gate in that
 * repo was silently dark. Nothing in the repo tested hook installation at all.
 *
 * So these tests assert reachability BY EXECUTION: build a hook, install over it, RUN
 * the resulting hook, and check the Speck payload printed. Grepping for the marker is
 * exactly the assertion that passes on the dead-block case this fixes — the marker is
 * present in the broken file too. Only running it can tell the difference.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, chmodSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { smartSync } from './sync.js';

const GATE_MARK = 'SPECK_GATE_RAN';

/** A pre-commit.com generated hook, verbatim in shape: top-level `exec` as the last line. */
const PRECOMMIT_COM_HOOK = `#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
ARGS+=(--color=always)
ARGS+=(-- "$@")
exec echo "PRECOMMIT_COM_RAN"
`;

/** The husky/hand-rolled variant of the same shadow: an unconditional top-level exit. */
const EXIT_TERMINATED_HOOK = `#!/usr/bin/env bash
set -e
echo "LEGACY_HOOK_RAN"
exit 0
`;

/** A well-behaved existing hook — nothing shadows the tail, so appending is correct. */
const PLAIN_HOOK = `#!/usr/bin/env bash
echo "PLAIN_HOOK_RAN"
`;

function makeWorkspace(existingPreCommit, existingCommitMsg) {
  const source = mkdtempSync(join(tmpdir(), 'speck-hooks-src-'));
  const target = mkdtempSync(join(tmpdir(), 'speck-hooks-tgt-'));
  // Minimal but real source tree — smartSync needs something to copy.
  mkdirSync(join(source, '.cursor', 'skills', 'speck'), { recursive: true });
  writeFileSync(join(source, '.cursor', 'skills', 'speck', 'SKILL.md'), 'shipped');

  mkdirSync(join(target, '.git', 'hooks'), { recursive: true });
  if (existingPreCommit) {
    writeFileSync(join(target, '.git', 'hooks', 'pre-commit'), existingPreCommit, { mode: 0o755 });
  }
  if (existingCommitMsg) {
    writeFileSync(join(target, '.git', 'hooks', 'commit-msg'), existingCommitMsg, { mode: 0o755 });
  }
  return { source, target };
}

/**
 * Drop in the scripts the installed loaders shell out to. Written AFTER sync, because the
 * loader resolves them relative to the repo root at commit time — which is exactly how a
 * real project's gates are reached.
 */
function installFakeGates(target) {
  const dir = join(target, '.speck', 'scripts', 'validation');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'pre-commit-hook.sh'), `#!/usr/bin/env bash\necho "${GATE_MARK}"\n`, { mode: 0o755 });
  writeFileSync(join(dir, 'commit-msg-hook.sh'), `#!/usr/bin/env bash\necho "${GATE_MARK} msg=$1"\n`, { mode: 0o755 });
}

/** Overwrite a gate so it FAILS, the way a real blocked commit does. */
function makeGateFail(target, name) {
  writeFileSync(
    join(target, '.speck', 'scripts', 'validation', `${name}-hook.sh`),
    `#!/usr/bin/env bash\necho "${GATE_MARK}"\nexit 1\n`,
    { mode: 0o755 }
  );
}

/** Run the installed hook the way git runs it: from the repo root. */
function runHook(target, name, args = [], env = {}) {
  const hookPath = join(target, '.git', 'hooks', name);
  chmodSync(hookPath, 0o755);
  return execFileSync('bash', [hookPath, ...args], {
    cwd: target,
    encoding: 'utf8',
    env: { ...process.env, ...env },
  });
}

/** Run a hook that is expected to fail; returns its exit status. */
function runHookStatus(target, name, args = []) {
  try {
    runHook(target, name, args);
    return 0;
  } catch (e) {
    return e.status;
  }
}

test('pre-commit: Speck block is REACHABLE when installed over a pre-commit.com hook', () => {
  const { source, target } = makeWorkspace(PRECOMMIT_COM_HOOK, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  // The whole defect in one assertion: the block is in the file either way, but only a
  // reachable block prints.
  assert.match(out, new RegExp(GATE_MARK), `Speck gate never executed — hook body was:\n${readFileSync(join(target, '.git', 'hooks', 'pre-commit'), 'utf8')}\ngot output: ${JSON.stringify(out)}`);
});

test('pre-commit: the pre-existing hook still runs too (we rescue, we do not displace)', () => {
  const { source, target } = makeWorkspace(PRECOMMIT_COM_HOOK, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  assert.match(out, /PRECOMMIT_COM_RAN/, `pre-commit.com's own body must survive; got: ${JSON.stringify(out)}`);
});

test('pre-commit: an `exit 0` terminated hook is rescued the same way', () => {
  const { source, target } = makeWorkspace(EXIT_TERMINATED_HOOK, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  assert.match(out, new RegExp(GATE_MARK), `Speck gate never executed past the unconditional exit; got: ${JSON.stringify(out)}`);
  assert.match(out, /LEGACY_HOOK_RAN/, 'the legacy hook body must still run');
});

test('pre-commit: a hook with no shadowing tail still gets the block, still executes', () => {
  const { source, target } = makeWorkspace(PLAIN_HOOK, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  assert.match(out, /PLAIN_HOOK_RAN/);
  assert.match(out, new RegExp(GATE_MARK));
});

test('pre-commit: a fresh install (no existing hook) executes', () => {
  const { source, target } = makeWorkspace(null, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  assert.match(out, new RegExp(GATE_MARK));
});

test('pre-commit: re-syncing is idempotent — one block, still reachable', () => {
  const { source, target } = makeWorkspace(PRECOMMIT_COM_HOOK, null);
  smartSync(source, target);
  smartSync(source, target);
  installFakeGates(target);

  const body = readFileSync(join(target, '.git', 'hooks', 'pre-commit'), 'utf8');
  const starts = body.split('# === SPECK HOOK START ===').length - 1;
  assert.equal(starts, 1, `expected exactly one Speck block after two syncs, found ${starts}`);
  assert.match(runHook(target, 'pre-commit'), new RegExp(GATE_MARK));
});

test('pre-commit: a block installed DEAD by an older Speck is rescued on upgrade', () => {
  // The actual upgrade path for every downstream repo that already ran the broken installer:
  // the marker is present, so the old code took the "update in place" branch and faithfully
  // kept the block exactly where it could never run.
  const dead = `${PRECOMMIT_COM_HOOK}
# === SPECK HOOK START ===
if [ -f .speck/scripts/validation/pre-commit-hook.sh ]; then
  bash .speck/scripts/validation/pre-commit-hook.sh
fi
# === SPECK HOOK END ===
`;
  const { source, target } = makeWorkspace(dead, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  assert.match(out, new RegExp(GATE_MARK), `an already-dead block must be relocated, not refreshed in place; got: ${JSON.stringify(out)}`);
  const body = readFileSync(join(target, '.git', 'hooks', 'pre-commit'), 'utf8');
  assert.equal(body.split('# === SPECK HOOK START ===').length - 1, 1, 'the dead copy must be removed, not duplicated');
});

test('pre-commit: `exec` used only for redirection is NOT treated as a terminator', () => {
  // `exec >log 2>&1` rewires the current shell's descriptors and execution continues.
  // Misreading it as a process replacement would relocate the block for no reason — and
  // relocation changes gate ordering, so it must happen only when it is actually needed.
  const redirecting = `#!/usr/bin/env bash
exec 2>&1
echo "REDIRECT_HOOK_RAN"
`;
  const { source, target } = makeWorkspace(redirecting, null);
  smartSync(source, target);
  installFakeGates(target);

  const body = readFileSync(join(target, '.git', 'hooks', 'pre-commit'), 'utf8');
  const gateAt = body.indexOf('# === SPECK HOOK START ===');
  const echoAt = body.indexOf('echo "REDIRECT_HOOK_RAN"');
  assert.ok(gateAt > echoAt, 'no terminator ⇒ the block still appends at the end');
  const out = runHook(target, 'pre-commit');
  assert.match(out, new RegExp(GATE_MARK));
  assert.match(out, /REDIRECT_HOOK_RAN/);
});

test('pre-commit: a FAILING gate still blocks the commit after relocation', () => {
  // Relocation has a trap in it. Appended last, the block was the final command, so the
  // hook's exit status WAS the gate's status and a failure blocked the commit for free.
  // Moved above the project's own body, a bare `if …; then bash gate; fi` no longer decides
  // the exit status — the gate would run, print its complaint, and the commit would sail
  // through. That is the same dead-guard failure wearing a different hat, so the loader has
  // to propagate the status explicitly.
  const { source, target } = makeWorkspace(PRECOMMIT_COM_HOOK, null);
  smartSync(source, target);
  installFakeGates(target);
  makeGateFail(target, 'pre-commit');

  assert.notEqual(runHookStatus(target, 'pre-commit'), 0, 'a failing Speck gate must fail the hook');
});

test('pre-commit: a FAILING gate still blocks the commit when appended (no terminator)', () => {
  const { source, target } = makeWorkspace(PLAIN_HOOK, null);
  smartSync(source, target);
  installFakeGates(target);
  makeGateFail(target, 'pre-commit');

  assert.notEqual(runHookStatus(target, 'pre-commit'), 0, 'a failing Speck gate must fail the hook');
});

test('commit-msg: a FAILING gate still blocks the commit after relocation', () => {
  const { source, target } = makeWorkspace(null, PRECOMMIT_COM_HOOK);
  smartSync(source, target);
  installFakeGates(target);
  makeGateFail(target, 'commit-msg');

  const msgFile = join(target, 'COMMIT_EDITMSG');
  writeFileSync(msgFile, 'bad message\n');
  assert.notEqual(runHookStatus(target, 'commit-msg', [msgFile]), 0, 'a failing Speck gate must fail the hook');
});

test('pre-commit: an unindented `exit` INSIDE a guard is not a top-level terminator', () => {
  // The relocation is only ever legitimate when the terminator really does shadow the tail.
  // Column 0 is not the same thing as top level: a hand-rolled hook whose body is not indented
  // puts its `exit 0` at column 0 while it sits inside `if … fi`, so it fires only on the
  // guard's condition. Reading that as unconditional splices Speck's block ABOVE the guard —
  // and with `|| exit $?` now making the block fatal, the repo's own documented bypass stops
  // exempting Speck's gates and the gate can block a commit the repo deliberately exempted.
  const skipGuard = `#!/usr/bin/env bash
if [ -n "$SKIP_HOOKS" ]; then
echo "SKIPPING"
exit 0
fi
echo "PROJECT_WORK_RAN"
`;
  const { source, target } = makeWorkspace(skipGuard, null);
  smartSync(source, target);
  installFakeGates(target);

  const skipped = runHook(target, 'pre-commit', [], { SKIP_HOOKS: '1' });
  assert.doesNotMatch(
    skipped,
    new RegExp(GATE_MARK),
    `the repo's own bypass must still exempt Speck's gates; hook body was:\n${readFileSync(join(target, '.git', 'hooks', 'pre-commit'), 'utf8')}\ngot output: ${JSON.stringify(skipped)}`
  );
  assert.match(skipped, /SKIPPING/, 'the guard itself must still fire');

  // …and with the bypass off, nothing is lost: both the project body and the gate run.
  const normal = runHook(target, 'pre-commit');
  assert.match(normal, /PROJECT_WORK_RAN/);
  assert.match(normal, new RegExp(GATE_MARK));
});

test('pre-commit: depth tracking closes again — a guard does not hide a real terminator below it', () => {
  // The other half of the depth fix. Declining to relocate is the safe direction, so a counter
  // that never comes back down would look correct while quietly restoring the original dead
  // block for every hook that happens to contain an `if` above its `exec`.
  const guarded = `#!/usr/bin/env bash
if [ -n "$SKIP_HOOKS" ]; then
exit 0
fi
exec echo "PROJECT_RAN"
`;
  const { source, target } = makeWorkspace(guarded, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  assert.match(out, new RegExp(GATE_MARK), `the exec below the guard still shadows the tail; got: ${JSON.stringify(out)}`);
  assert.match(out, /PROJECT_RAN/);
  // …and the bypass still wins, because the block sits below the guard, not above it.
  const skipped = runHook(target, 'pre-commit', [], { SKIP_HOOKS: '1' });
  assert.doesNotMatch(skipped, new RegExp(GATE_MARK), `got: ${JSON.stringify(skipped)}`);
});

test('pre-commit: a column-0 `exit` inside a heredoc body is not a terminator', () => {
  // The block is now spliced immediately ABOVE the terminator, so a false terminator is no
  // longer merely a pointless relocation — it would splice Speck's block into the middle of
  // someone's heredoc, corrupting their text AND leaving the gate dark inside it. A heredoc
  // body is data, not code, so the scan has to know where one is.
  const heredoc = `#!/usr/bin/env bash
cat <<EOF
Speck usage:
exit 0
EOF
echo "HEREDOC_HOOK_RAN"
`;
  const { source, target } = makeWorkspace(heredoc, null);
  smartSync(source, target);
  installFakeGates(target);

  const body = readFileSync(join(target, '.git', 'hooks', 'pre-commit'), 'utf8');
  assert.ok(
    body.indexOf('# === SPECK HOOK START ===') > body.indexOf('EOF\n'),
    `the block must not land inside the heredoc; body was:\n${body}`
  );
  const out = runHook(target, 'pre-commit');
  assert.match(out, /HEREDOC_HOOK_RAN/);
  assert.match(out, new RegExp(GATE_MARK));
});

test('pre-commit: a terminator continued onto from the line above is left alone', () => {
  // `printf '%s\\n' \\` + `exec` is an ARGUMENT, not a process replacement, and splicing between
  // the two halves would break the command outright. When the shape is ambiguous we decline to
  // relocate — appending is what pre-9.6 Speck did, so declining can never turn a green repo red.
  const continued = `#!/usr/bin/env bash
printf '%s\\n' \\
exec echo "ARG"
echo "CONTINUED_HOOK_RAN"
`;
  const { source, target } = makeWorkspace(continued, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  assert.match(out, /CONTINUED_HOOK_RAN/, `the continued command must survive intact; got: ${JSON.stringify(out)}`);
  assert.match(out, new RegExp(GATE_MARK));
});

test('pre-commit: a CRLF pre-commit.com hook is rescued too', () => {
  // Windows/WSL-generated hooks arrive with CRLF line endings. In JS `.` does not match `\r`,
  // so /^exec[ \t]+(.+)$/ never matched `exec …\r` — the terminator scan came back empty, the
  // block was appended BELOW the exec exactly as before the fix, and nothing warned. A hook
  // authored on Windows kept a dark gate and looked identical to a healthy one.
  const crlf = PRECOMMIT_COM_HOOK.replace(/\n/g, '\r\n');
  const { source, target } = makeWorkspace(crlf, null);
  smartSync(source, target);
  installFakeGates(target);

  const out = runHook(target, 'pre-commit');
  assert.match(
    out,
    new RegExp(GATE_MARK),
    `a CRLF hook's exec shadows the tail exactly as an LF one does; hook body was:\n${JSON.stringify(readFileSync(join(target, '.git', 'hooks', 'pre-commit'), 'utf8'))}\ngot output: ${JSON.stringify(out)}`
  );
  assert.match(out, /PRECOMMIT_COM_RAN/, "the project's own body must survive");
});

test('pre-commit: relocation lands AFTER the hook environment setup', () => {
  // Relocation puts the block as early as it legally can, and "as early as legal" used to mean
  // above everything but the shebang and `set`/`shopt`. A hook that sets up nvm/asdf/pyenv (or
  // any PATH export) before its terminator therefore ran Speck's gates in a DIFFERENT
  // environment than the project intended — which silently changes which sub-gates degrade,
  // because they probe for python3/rg on PATH. Proven by execution, not by line numbers: the
  // gate looks for a tool that only the project's own PATH export can reach.
  const { source, target } = makeWorkspace(null, null);
  const binDir = join(target, 'projectbin');
  mkdirSync(binDir, { recursive: true });
  writeFileSync(join(binDir, 'speck-env-probe'), '#!/usr/bin/env bash\necho probe\n', { mode: 0o755 });

  const envHook = `#!/usr/bin/env bash
export PATH="${binDir}:$PATH"
exec echo "PROJECT_RAN"
`;
  writeFileSync(join(target, '.git', 'hooks', 'pre-commit'), envHook, { mode: 0o755 });
  smartSync(source, target);

  const dir = join(target, '.speck', 'scripts', 'validation');
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, 'pre-commit-hook.sh'),
    `#!/usr/bin/env bash\necho "${GATE_MARK}"\nif command -v speck-env-probe >/dev/null 2>&1; then echo "PROJECT_PATH_VISIBLE"; fi\n`,
    { mode: 0o755 }
  );

  const out = runHook(target, 'pre-commit');
  assert.match(out, new RegExp(GATE_MARK), 'the gate must still be reachable');
  assert.match(
    out,
    /PROJECT_PATH_VISIBLE/,
    `the gate must see the environment the project set up; hook body was:\n${readFileSync(join(target, '.git', 'hooks', 'pre-commit'), 'utf8')}\ngot output: ${JSON.stringify(out)}`
  );
  assert.match(out, /PROJECT_RAN/, "the project's own body must survive");
});

test('commit-msg: same shadow, same rescue — and $1 still reaches the gate', () => {
  const { source, target } = makeWorkspace(null, PRECOMMIT_COM_HOOK);
  smartSync(source, target);
  installFakeGates(target);

  const msgFile = join(target, 'COMMIT_EDITMSG');
  writeFileSync(msgFile, 'chore: test\n');
  const out = runHook(target, 'commit-msg', [msgFile]);
  assert.match(out, new RegExp(GATE_MARK), `commit-msg gate never executed; got: ${JSON.stringify(out)}`);
  // The argument must survive the relocation — a gate that runs on the wrong file is
  // no better than one that never runs.
  assert.match(out, new RegExp(`msg=${msgFile.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`));
});
