name: django-htmx
display_name: "Django + HTMX"
description: A Python-based full-stack web application using Django with HTMX for modern, interactive UIs without heavy JavaScript frameworks. Excellent for rapid development and content-heavy applications.
version: "1.0.0"
keywords:
  - web
  - full-stack
  - django
  - python
  - htmx
  - postgresql
  - server-rendered
  - hypermedia
stack:
  frontend:
    name: Django Templates + HTMX
    language: HTML / Python (templates)
    framework: HTMX + Alpine.js
    styling: Tailwind CSS / Bootstrap
  backend:
    name: Django
    language: Python
    framework: Django
    orm: Django ORM
  database:
    name: PostgreSQL
    version: "15"
suggested_epics:
  - name: Developer Infrastructure
    description: Testing (pytest-django), CI/CD pipeline, linting (Ruff), error tracking (Sentry), environment config
    stories_estimate: 3-5
    priority: 0
    phase: foundation
    
  - name: User Authentication & Authorization
    description: Implement Django's built-in auth with custom user model, permissions, and groups.
    stories_estimate: 5-8
  - name: HTMX Interactive Features
    description: Build dynamic UI components using HTMX for partial page updates, infinite scroll, and real-time validation.
    stories_estimate: 8-12
  - name: Django Admin Customization
    description: Configure and extend Django Admin for content management and internal tools.
    stories_estimate: 4-6
  - name: API Layer (Optional DRF)
    description: Add Django REST Framework for mobile app support or third-party integrations.
    stories_estimate: 6-9
pre_configured_patterns:
  - name: Class-Based Views
    description: Leverage Django's powerful CBVs for CRUD operations.
  - name: HTMX Patterns
    description: hx-get, hx-post, hx-swap for seamless interactivity.
  - name: Django Signals
    description: Event-driven architecture for decoupled logic.


# Visual testing configuration
visual_testing:
  platform: web
  strategy: browser-mcp
  pattern_file: "visual-testing/web-visual-testing.md"
  breakpoints:
    mobile: 375
    tablet: 768
    desktop: 1024
    wide: 1280
  tools:
    primary: playwright
    storybook: false
    visual_regression: percy
  agent_commands:
    screenshot: "browser_take_screenshot"
    audit_a11y: "runAccessibilityAudit"
    audit_perf: "runPerformanceAudit"
    playwright_test: "npx playwright test"
    playwright_update: "npx playwright test --update-snapshots"
  ci_integration:
    on_pr: true
    block_on_diff: true
