name: "🤖 Speck Story"
description: "Create a Speck story for Copilot Agent"
title: "[EPIC] STORY: TITLE"
labels: ["speck:story", "automated", "speck:queued"]
body:
  - type: input
    id: epic_id
    attributes:
      label: Epic ID
      description: "Epic identifier from epics/ directory"
    validations:
      required: true

  - type: input
    id: story_id
    attributes:
      label: Story ID
      description: "Story identifier from stories/ directory"
    validations:
      required: true

  - type: input
    id: story_title
    attributes:
      label: Story Title
      description: "Human-readable story title"
    validations:
      required: true

  - type: dropdown
    id: current_phase
    attributes:
      label: Current Phase
      description: "Where is this story in the Speck flow?"
      options:
        - "unspecced - needs story-specify"
        - "specified - needs story-clarify"  
        - "clarified - needs story-plan"
        - "planned - needs story-tasks"
        - "tasked - needs story-analyze"
        - "analyzed - needs story-implement"
        - "implemented - needs story-validate"
    validations:
      required: true

  - type: textarea
    id: epic_context
    attributes:
      label: Epic Context
      description: "Brief description of the parent epic's goals"

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: "Story IDs this depends on (comma-separated)"

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Command Flow (MUST follow in order)
        
        ### Discovery & Specification
        1. `story-specify` → Creates `spec.md`
        2. `story-clarify` → Resolves ambiguities
        3. `story-outline` → *(optional)* Research needs mapping
        4. `story-scan` → *(optional, brownfield)* Existing code analysis
        
        ### Planning  
        5. `story-plan` → Creates `plan.md`, `data-model.md`, `contracts/`
        6. `story-ui-spec` → *(optional, UI-heavy)* Detailed UI specs
        
        ### Execution
        7. `story-tasks` → Creates `tasks.md`
        8. `story-analyze` → ⚠️ **REQUIRED** Quality check before implementation
        9. `story-implement` → Write code, create PR
        
        ### Validation
        10. `story-validate` → Validates implementation, creates `validation-report.md`
        
        ---
        
        ## Critical Rules
        
        ✅ **ALWAYS** run `story-analyze` before `story-implement`  
        ✅ **ALWAYS** run `story-validate` after implementation  
        ✅ **ALWAYS** follow exact templates in `.speck/templates/story/`  
        ✅ **NEVER** skip required commands  
        
        ## Completion Criteria
        
        A story is **complete** when `validation-report.md` exists with status PASS.
        
        ## Decision Gates for Optional Commands
        
        | Command | When to Include |
        |---------|-----------------|
        | `story-outline` | Complex technical decisions, unfamiliar tech stack |
        | `story-scan` | Extending existing codebase (brownfield) |
        | `story-ui-spec` | UI-heavy story with multiple components/states |
