name: "🤖 Speck Story"
description: "Create a Speck story for Copilot Agent"
title: "[EPIC_ID] STORY_ID: STORY_TITLE"
labels: ["speck:story", "automated", "speck:queued"]
body:
  - type: input
    id: epic_id
    attributes:
      label: Epic ID
      description: "Epic identifier (e.g., 001-app-shell)"
      placeholder: "001-app-shell"
    validations:
      required: true

  - type: input
    id: story_id
    attributes:
      label: Story ID
      description: "Story identifier (e.g., S001-project-setup)"
      placeholder: "S001-project-setup"
    validations:
      required: true

  - type: input
    id: story_title
    attributes:
      label: Story Title
      description: "Human-readable story title"
      placeholder: "Initial Project Setup"
    validations:
      required: true

  - type: dropdown
    id: current_phase
    attributes:
      label: Current Phase
      description: "Where is this story in the Speck flow?"
      options:
        - "unspecced - needs story-specify"
        - "specified - needs story-clarify"  
        - "clarified - needs story-plan"
        - "planned - needs story-tasks"
        - "tasked - needs story-analyze then story-implement"
    validations:
      required: true

  - type: textarea
    id: epic_context
    attributes:
      label: Epic Context
      description: "Brief description of the parent epic's goals"
      placeholder: "This epic establishes the app shell and design system..."

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: "Story IDs this depends on (comma-separated)"
      placeholder: "S001-project-setup, S002-auth-setup"

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Command Flow (MUST follow in order)
        
        ### Discovery & Specification
        1. `story-specify` → Creates `spec.md`
        2. `story-clarify` → Resolves ambiguities
        3. `story-outline` → *(optional)* Research needs mapping
        4. `story-scan` → *(optional, brownfield)* Existing code analysis
        
        ### Planning  
        5. `story-plan` → Creates `plan.md`, `data-model.md`, `contracts/`
        6. `story-ui-spec` → *(optional, UI-heavy)* Detailed UI specs
        
        ### Execution
        7. `story-tasks` → Creates `tasks.md` with **EXACT** format:
           ```
           - [ ] T001 Task description
           - [ ] T002 [P] Parallel task
           ```
        8. `story-analyze` → ⚠️ **REQUIRED** Quality check before implementation
        9. `story-implement` → Write code, create PR
        
        ### Post-PR (handled by other workflows)
        - `story-validate` → Via `speck-validate-pr.yml`
        - `story-retrospective` → Via `speck-retrospective.yml`
        
        ---
        
        ## Critical Rules
        
        ✅ **ALWAYS** run `story-analyze` before `story-implement`  
        ✅ **ALWAYS** follow exact templates in `.speck/templates/story/`  
        ✅ **NEVER** skip required commands  
        
        ## Decision Gates for Optional Commands
        
        | Command | When to Include |
        |---------|-----------------|
        | `story-outline` | Complex technical decisions, unfamiliar tech stack |
        | `story-scan` | Extending existing codebase (brownfield) |
        | `story-ui-spec` | UI-heavy story with multiple components/states |
