#!/usr/bin/env bash
# check-replace-markers.test.sh — smoke tests for the REPLACE_BEFORE_SHIP lint
#
# #89: a plain `grep "REPLACE_BEFORE_SHIP:"` convicted Speck's own templates
# for NAMING the marker in a heading, an explanatory sentence, and a worked
# `grep` example inside a fenced code block — three permanent, un-clearable
# false positives in every scaffolded project. The fix distinguishes a
# GENUINE unfilled marker (real hint text after the colon) from the
# convention-describing form (immediately closed by a backtick/quote, or the
# literal <hint> meta-placeholder) STRUCTURALLY, and strips fenced code
# blocks wholesale before scanning. Every case here is paired with the trap
# the reviewer flagged: a genuine marker written INSIDE backticks
# (`REPLACE_BEFORE_SHIP: pick a name`) must never be swallowed by the fix.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CRM="$ROOT/.speck/scripts/check-replace-markers.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$TMP/specs/projects/p/a" "$TMP/specs/projects/p/b"

echo "Test: heading + explanatory-sentence citation form (project-state-template.md shape) passes"
cat > "$TMP/citation-heading.md" <<'EOF'
## 🚧 Outstanding `REPLACE_BEFORE_SHIP` markers

*Auto-populated. Any truth artifact carrying an unfilled `REPLACE_BEFORE_SHIP` token is incomplete and cannot claim ship-readiness. Generated by:*
EOF
bash "$CRM" "$TMP/citation-heading.md"

echo "Test: bare backtick-closed token citation ('\`REPLACE_BEFORE_SHIP:\`') passes"
cat > "$TMP/citation-backtick.md" <<'EOF'
Any truth artifact carrying a `REPLACE_BEFORE_SHIP:` token is incomplete.
EOF
bash "$CRM" "$TMP/citation-backtick.md"

echo "Test: old PLACEHOLDER CONVENTION wording (literal <hint> meta-placeholder, copied into already-scaffolded projects) passes"
cat > "$TMP/citation-hint-meta.md" <<'EOF'
PLACEHOLDER CONVENTION:
  Tokens marked  REPLACE_BEFORE_SHIP: <hint>  MUST be filled before this artifact
  can claim ship-readiness. /speck-recheck greps for them.
EOF
bash "$CRM" "$TMP/citation-hint-meta.md"

echo "Test: worked grep example inside a fenced code block (project-state-template.md :109 case, PINNED) passes"
cat > "$TMP/fenced-example.md" <<'EOF'
## 🚧 Outstanding `REPLACE_BEFORE_SHIP` markers

*Auto-populated. Generated by:*

```bash
grep -rln "REPLACE_BEFORE_SHIP:" specs/projects/<PROJECT_ID>/
```

If empty: "No outstanding REPLACE_BEFORE_SHIP markers."
EOF
bash "$CRM" "$TMP/fenced-example.md"

echo "Test: TRAP — a genuine unfilled marker in plain prose must still be caught"
cat > "$TMP/trap-plain.md" <<'EOF'
**Project**: REPLACE_BEFORE_SHIP: PROJECT_NAME
EOF
if bash "$CRM" "$TMP/trap-plain.md" >/dev/null 2>&1; then
  echo "FAIL: a genuine unfilled plain-prose marker was wrongly allowed through"
  exit 1
fi

echo "Test: TRAP — a genuine unfilled marker INSIDE BACKTICKS must still be caught (the reviewer's trap)"
cat > "$TMP/trap-backtick.md" <<'EOF'
- **SHA at decision time**: `REPLACE_BEFORE_SHIP: pick a name`
EOF
if bash "$CRM" "$TMP/trap-backtick.md" >/dev/null 2>&1; then
  echo "FAIL: a genuine unfilled backtick-wrapped marker was wrongly allowed through — this is exactly"
  echo "      the false-positive-becomes-false-negative trap a blanket backtick-strip would cause."
  exit 1
fi

# P1-1 (adversarial review, #93): the #89 fix over-corrected. It exempted ANY
# line where a backtick/quote/end-of-line followed the colon, on the theory
# that a genuine marker always carries real hint content right after the
# colon. False — three genuine unfilled shapes were newly swallowed, turning
# the original false POSITIVE into a false NEGATIVE (the exact inversion the
# header above claims this script avoids). Each must still be caught.

echo "Test: TRAP (P1-1a) — colon at end of line (hint deleted, never filled) must still be caught"
cat > "$TMP/trap-eol.md" <<'EOF'
**Name**: REPLACE_BEFORE_SHIP:
EOF
if bash "$CRM" "$TMP/trap-eol.md" >/dev/null 2>&1; then
  echo "FAIL: a marker with nothing after the colon (the most genuine unfilled shape there is) was"
  echo "      wrongly allowed through by the old \$-alternation exemption."
  exit 1
fi

echo "Test: TRAP (P1-1b) — hint that opens with a double quote must still be caught"
cat > "$TMP/trap-quote-hint.md" <<'EOF'
**Promise**: REPLACE_BEFORE_SHIP: "one honest sentence"
EOF
if bash "$CRM" "$TMP/trap-quote-hint.md" >/dev/null 2>&1; then
  echo "FAIL: a genuine unfilled marker whose hint text opens with a double quote was wrongly"
  echo "      allowed through — an open-delimiter exemption is not the same as a CITATION."
  exit 1
fi

echo "Test: TRAP (P1-1c) — hint that opens with a backtick must still be caught"
cat > "$TMP/trap-backtick-hint.md" <<'EOF'
**Id**: REPLACE_BEFORE_SHIP: `project-id-here`
EOF
if bash "$CRM" "$TMP/trap-backtick-hint.md" >/dev/null 2>&1; then
  echo "FAIL: a genuine unfilled marker whose hint text opens with a backtick was wrongly allowed"
  echo "      through — only a marker CITED as \`REPLACE_BEFORE_SHIP:\` (nothing between the colon"
  echo "      and its own closing backtick) may be exempt."
  exit 1
fi

echo "  ✓ all citation-form cases pass, all five genuine-marker traps still fail"

# P2-2 (adversarial review, #93): sp_blank_fenced_code() had zero independent
# coverage and blanked EVERY fenced code block wholesale, regardless of
# language — so a genuine unfilled marker pasted inside ANY fenced block
# (a YAML snippet, a copied file-tree, a markdown excerpt) in a downstream
# artifact was silently invisible to this scanner. The fix narrows the blank
# to shell/console-tagged fences only (```bash/sh/shell/zsh/console), the one
# class of fence Speck's own templates actually use for the worked
# `grep "REPLACE_BEFORE_SHIP:"` citation example. These cases defend that
# boundary directly, independent of the templates.

echo "Test: sp_blank_fenced_code (P2-2) — a genuine marker inside a NON-shell-tagged fenced block must still be caught"
cat > "$TMP/fence-nonshell.md" <<'EOF'
Some prose.

```yaml
name: REPLACE_BEFORE_SHIP: pick a name
```
EOF
if bash "$CRM" "$TMP/fence-nonshell.md" >/dev/null 2>&1; then
  echo "FAIL: a genuine unfilled marker inside a non-shell fenced block was wrongly swallowed —"
  echo "      the fenced-block blank must be narrowed to shell/console fences only (P2-2)."
  exit 1
fi

echo "Test: sp_blank_fenced_code (P2-2) — a genuine marker inside an UNTAGGED (language-less) fenced block must still be caught"
cat > "$TMP/fence-untagged.md" <<'EOF'
Some prose.

```
name: REPLACE_BEFORE_SHIP: pick a name
```
EOF
if bash "$CRM" "$TMP/fence-untagged.md" >/dev/null 2>&1; then
  echo "FAIL: a genuine unfilled marker inside an untagged fenced block was wrongly swallowed."
  exit 1
fi

echo "Test: sp_blank_fenced_code (P2-2) — a shell-tagged fence still exempts the worked CLI citation example"
cat > "$TMP/fence-shell-citation.md" <<'EOF'
```bash
grep -rln "REPLACE_BEFORE_SHIP:" specs/projects/<PROJECT_ID>/
```
EOF
bash "$CRM" "$TMP/fence-shell-citation.md"
echo "  ✓ non-shell/untagged fences are scanned for real, shell-fenced worked examples stay exempt"

echo "Test: directory mode — mixed clean + dirty files reports only the dirty one"
cp "$TMP/citation-heading.md" "$TMP/specs/projects/p/a/clean.md"
cp "$TMP/trap-backtick.md" "$TMP/specs/projects/p/b/dirty.md"
if OUT="$(bash "$CRM" "$TMP/specs" 2>&1)"; then EC=0; else EC=$?; fi
if [[ "$EC" -eq 0 ]]; then
  echo "FAIL: directory scan passed despite dirty.md containing a genuine unfilled marker"
  exit 1
fi
if printf '%s\n' "$OUT" | grep -q "clean.md"; then
  echo "FAIL: clean.md was wrongly named in a mixed directory scan:"
  echo "$OUT"
  exit 1
fi
if ! printf '%s\n' "$OUT" | grep -q "dirty.md"; then
  echo "FAIL: dirty.md was NOT named despite containing a genuine unfilled marker:"
  echo "$OUT"
  exit 1
fi
echo "  ✓ only the genuinely-dirty file was named"

echo "Test: directory mode — an all-citation-form directory passes"
rm "$TMP/specs/projects/p/b/dirty.md"
bash "$CRM" "$TMP/specs"

echo "Test: empty directory passes"
mkdir -p "$TMP/empty-specs"
bash "$CRM" "$TMP/empty-specs"

echo "All check-replace-markers smoke tests passed"
