#!/usr/bin/env bash
# check-replace-markers.sh — Pre-ship lint for REPLACE_BEFORE_SHIP tokens
#
# Usage:
#   .speck/scripts/check-replace-markers.sh [path]
#
# Behavior:
#   - Scans the given path (default: specs/) recursively for a GENUINE,
#     unfilled REPLACE_BEFORE_SHIP marker in a .md file — see "WHY NOT A
#     PLAIN grep" below, this is not a literal-substring search.
#   - Reports artifact + line + count.
#   - Exit code 0: clean.
#   - Exit code 1: at least one token found — artifact cannot claim ship-readiness.
#
# Speck v7.2+ pattern. Any truth artifact carrying this token is incomplete.
# /speck-recheck and /story-validate / /epic-validate / /project-validate
# call this script and refuse to advance the readiness state past IMPL-GREEN
# while any tokens remain.
#
# --- WHY NOT A PLAIN grep (#89) ---------------------------------------------
# Speck's OWN templates have to NAME the REPLACE_BEFORE_SHIP token to explain
# the convention to a reader: project-state-template.md's permanently-
# required "Outstanding REPLACE_BEFORE_SHIP markers" section (a heading, an
# explanatory sentence, and a worked `grep "REPLACE_BEFORE_SHIP:"` example
# inside a fenced code block), plus the PLACEHOLDER CONVENTION comment
# repeated near the top of evidence-contract / project-decisions-log /
# product-contract templates. A plain substring grep for
# "REPLACE_BEFORE_SHIP:" convicted all of those — 3 permanent, un-clearable
# hits in every scaffolded project, filed as #89. Worse: because
# project-state.md is regenerated by Speck itself after every truth-affecting
# command, and project-decisions-log.md is appended at every phase boundary
# as "unconditional discipline" (speck-decision-log), a project that wired
# this script into pre-commit reached a state where Speck's OWN generated
# output could not be committed.
#
# The fix is NOT "strip inline code spans (single backticks) before
# matching". A genuine unfilled marker is routinely written inside backticks
# too — `REPLACE_BEFORE_SHIP: pick a name` is a real, valid unfilled field —
# and blanket backtick-stripping would silently turn that into a false
# NEGATIVE, which is worse than the false positive it replaces in a gate
# /speck-recheck treats as load-bearing.
#
# Instead, this script distinguishes the two forms STRUCTURALLY:
#   - A GENUINE marker always carries real hint content right after the
#     colon: REPLACE_BEFORE_SHIP: project-id, REPLACE_BEFORE_SHIP: pick a name.
#   - The convention-DESCRIBING form never does. It is either immediately
#     closed by a backtick/quote with nothing in between
#     (`REPLACE_BEFORE_SHIP:`), or it spells the literal <hint>
#     meta-placeholder from the old PLACEHOLDER CONVENTION wording — which is
#     still present verbatim in every project scaffolded before this fix, so
#     a template-only reword does not heal those; the script has to know the
#     difference too.
# Fenced code blocks (```...```) are stripped wholesale before scanning:
# their one legitimate use of the token in Speck's own templates is the
# worked `grep "REPLACE_BEFORE_SHIP:"` example, quoting the pattern as a
# string literal to run, not a field to fill in.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/text.sh
. "$SCRIPT_DIR/lib/text.sh"

ROOT="${1:-specs/}"

# P1-1 (#93): the original version of this fix EXEMPTED any line where a
# backtick, double-quote, or end-of-line followed the colon, on the theory
# that "a genuine marker always carries real hint content right after the
# colon". That's an assumption, not a fact, and it was wrong three ways —
# turning the original false POSITIVE (#89) into a false NEGATIVE, the exact
# inversion this script's header claims to avoid:
#   - REPLACE_BEFORE_SHIP:                          (colon ends the line —
#     the CANONICAL shape of a hint that was deleted and never filled; the
#     single most genuine unfilled marker there is, never a citation)
#   - REPLACE_BEFORE_SHIP: "one honest sentence"     (a real hint is allowed
#     to open with a quote)
#   - REPLACE_BEFORE_SHIP: `project-id-here`         (a real hint is allowed
#     to open with a backtick)
# An open delimiter right after the colon is not evidence of a citation —
# it's just as often the FIRST character of a genuine hint. So this matches
# the CITATION shapes POSITIVELY instead: the marker (including its own
# colon) wrapped by a SINGLE pair of backticks/quotes with NOTHING else
# inside (`REPLACE_BEFORE_SHIP:` or "REPLACE_BEFORE_SHIP:" — the delimiter
# closes immediately, right where it opened, so it can only be quoting the
# token itself, never introducing hint content), or the literal <hint>
# meta-placeholder. Matched unanchored against a single line's full content
# (after the leading "LINE:" grep prefix has been stripped by the caller) —
# the character immediately before "REPLACE_BEFORE_SHIP" is preserved in
# that content, so the opening delimiter of a wrapping citation is still
# visible to the match even though the regex only anchors on what follows
# the colon.
CITATION_RE='`REPLACE_BEFORE_SHIP:`|"REPLACE_BEFORE_SHIP:"|REPLACE_BEFORE_SHIP:[[:space:]]*<hint>'

# sp_blank_fenced_code <file>
# Emit the file with every line inside a SHELL/CONSOLE fenced code block
# (```bash, ```sh, ```shell, ```zsh, ```console — case-insensitive info
# string) replaced by an empty line. Line COUNT is preserved (blanked, not
# deleted) so the line numbers reported below still point at the real source
# line. Any OTHER fence (```yaml, ```md, or a bare ``` with no language tag)
# is left untouched and scanned normally.
#
# P2-2 (#93): this used to blank EVERY fenced block, any language, wholesale.
# The only legitimate reason to blank a fence at all is Speck's own worked
# `grep "REPLACE_BEFORE_SHIP:"` CLI example — always tagged ```bash — so
# blanking every OTHER fence too bought no coverage and cost real coverage: a
# genuine unfilled marker pasted inside a YAML snippet, a copied file-tree,
# or any other fenced example in a downstream artifact was invisible to this
# scanner, in a gate /speck-recheck treats as load-bearing. Narrowed to the
# one class of fence that actually needs it.
sp_blank_fenced_code() {
  awk '
    BEGIN { fenced = 0; blank = 0 }
    /^```/ {
      if (!fenced) {
        fenced = 1
        info = $0
        sub(/^```/, "", info)
        gsub(/^[[:space:]]+/, "", info)
        gsub(/[[:space:]]+$/, "", info)
        n = split(info, parts, /[[:space:]]+/)
        lang = tolower(parts[1])
        blank = (lang == "bash" || lang == "sh" || lang == "shell" || lang == "zsh" || lang == "console")
      } else {
        fenced = 0
        blank = 0
      }
      print ""
      next
    }
    fenced && blank { print ""; next }
    { print }
  ' "$1"
}

# sp_genuine_marker_hits <file>
# Print "LINE:content" for every line carrying a genuine (unfilled) marker.
# Empty output means the file is clean.
sp_genuine_marker_hits() {
  local f="$1" blanked candidates line content
  blanked="$(sp_blank_fenced_code "$f")"
  # Capture into a variable before testing anything — never `grep ... |
  # while read`, and never trust a pipeline's exit status under pipefail
  # (see text.sh's header): grep exits 1 on "no match", which is a normal,
  # expected outcome here, not a script failure.
  candidates="$(grep -n "REPLACE_BEFORE_SHIP:" <<<"$blanked" 2>/dev/null || true)"
  [[ -z "$candidates" ]] && return 0
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    content="${line#*:}"
    if [[ "$content" =~ $CITATION_RE ]]; then
      continue
    fi
    printf '%s\n' "$line"
  done <<<"$candidates"
}

if [[ ! -d "$ROOT" ]]; then
  if [[ -f "$ROOT" ]]; then
    HITS_OUT="$(sp_genuine_marker_hits "$ROOT")"
    HITS=0
    [[ -n "$HITS_OUT" ]] && HITS="$(printf '%s\n' "$HITS_OUT" | wc -l | tr -d ' ')"
    if [[ "$HITS" -eq 0 ]]; then
      echo "✅ check-replace-markers: $ROOT — clean"
      exit 0
    else
      echo "❌ check-replace-markers: $ROOT — $HITS token(s) remaining"
      while IFS= read -r hit; do
        echo "$ROOT:$hit"
      done <<<"$HITS_OUT"
      exit 1
    fi
  fi
  echo "ERROR: path not found: $ROOT" >&2
  exit 2
fi

# Coarse pre-filter first (cheap, catches any file mentioning the token at
# all, bare or genuine); sp_genuine_marker_hits then decides per file below
# whether any of those mentions are actually unfilled.
HIT_FILES=$(grep -rln --include='*.md' "REPLACE_BEFORE_SHIP:" "$ROOT" 2>/dev/null || true)

if [[ -z "$HIT_FILES" ]]; then
  echo "✅ check-replace-markers: $ROOT — clean (no REPLACE_BEFORE_SHIP tokens)"
  exit 0
fi

TOTAL=0
FILE_COUNT=0
REPORT=""

while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  hits="$(sp_genuine_marker_hits "$f")"
  [[ -z "$hits" ]] && continue
  count="$(printf '%s\n' "$hits" | wc -l | tr -d ' ')"
  REPORT="${REPORT}| $f | $count |"$'\n'
  TOTAL=$((TOTAL + count))
  FILE_COUNT=$((FILE_COUNT + 1))
done <<< "$HIT_FILES"

if [[ "$TOTAL" -eq 0 ]]; then
  echo "✅ check-replace-markers: $ROOT — clean (every REPLACE_BEFORE_SHIP mention describes the convention; none are unfilled)"
  exit 0
fi

echo "❌ check-replace-markers: $ROOT — REPLACE_BEFORE_SHIP tokens found"
echo ""
echo "| Artifact | Token count |"
echo "|----------|-------------|"
printf '%s' "$REPORT"

echo ""
echo "Total: $TOTAL token(s) remaining across $FILE_COUNT file(s)"
echo ""
echo "Resolution: every REPLACE_BEFORE_SHIP token must be filled or removed"
echo "before the artifact can claim a readiness state above IMPL-GREEN."

exit 1
